name: CI-feature-branch
concurrency: ci-${{ github.ref }}
on:
  push:
    branches: ["*", "!main", "!master", "!skip/*"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  create-a:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |
          echo -n 'the date is: ' >> a.txt
          date >> a.txt
      - name: Save a.txt
        uses: actions/upload-artifact@v3
        with:
          name: the_file_a.txt
          path: a.txt
  consume-a:
    needs: create-a
    runs-on: ubuntu-latest
    steps:
      - name: Get the_file_a.txt from a previous job
        uses: actions/download-artifact@v3
        with:
          name: the_file_a.txt
      - name: Display the file from a previous job
        run: |
          ls -a
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
        with:
          submodules: true
          persist-credentials: false

      - name: Install
        run: |
          npm install

      - name: Install frontend
        working-directory: frontend
        run: |
          npm install

      - name: Install backend
        working-directory: backend
        run: |
          npm install

      - name: Test backend
        working-directory: backend
        run: |
          npm test

      - name: Build
        run: |
          npm run build

      - name: Build frontend
        working-directory: frontend
        run: |
          npm run build

      - name: Test frontend
        working-directory: frontend
        run: |
          npm test

      - name: Install content
        working-directory: content
        run: |
          npm install

      - name: Test content
        working-directory: content
        run: |
          npm test

      - name: Test
        run: |
          npm test

      - name: Build backend prod artifact
        working-directory: backend
        run: |
          rm -rf node_modules
          npm install --production

      - name: Identify dev account and region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          aws sts get-caller-identity
          echo ${AWS_DEFAULT_REGION} | sed 's/-/+/g'

      - name: Deploy the webapp stack to dev account
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          npm run deploy-webapp

      - name: Deploy to the frontend bucket (dev account)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          npm run deploy-frontend

      - name: Deploy content (dev account)
        working-directory: content
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          bash deploy-content.sh

      - name: Install itest
        working-directory: itest
        run: |
          npm install

      - name: Run smoke test (dev account)
        working-directory: scripts
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_REGION: "us-east-1"
        run: |
          npm run itest
