name: CI-feature-branch
concurrency: ci-${{ github.ref }}
on:
  push:
    branches: ["*", "!main", "!master", "!skip/*"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  id-account:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEV_ROLE_ARN }}
          aws-region: us-east-1
      - name: Identify dev account and region
        run: |
          aws sts get-caller-identity
          echo ${AWS_DEFAULT_REGION} | sed 's/-/+/g'
  webapp:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: false
      - name: Install infra
        working-directory: infra
        run: |
          npm install
      - name: Install backend
        working-directory: backend
        run: |
          npm install
      - name: Test backend
        working-directory: backend
        run: |
          npm test
      - name: Install backend-v2
        working-directory: backend-v2
        run: |
          npm install
      - name: Test backend-v2
        working-directory: backend-v2
        run: |
          npm test
      - name: Build infra
        working-directory: infra
        run: |
          npm run build
      - name: Test infra
        working-directory: infra
        run: |
          npm test
      - name: Build backend prod artifact
        working-directory: backend
        run: |
          rm -rf node_modules
          npm install --production
      - name: Build backend-v2 prod artifact
        working-directory: backend-v2
        run: |
          rm -rf node_modules
          npm install --production
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEV_ROLE_ARN }}
          aws-region: us-east-1
      - name: Deploy the webapp stack to dev account
        working-directory: infra
        run: |
          npm run deploy-webapp
  frontend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: webapp
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEV_ROLE_ARN }}
          aws-region: us-east-1
      - name: Deploy to the frontend bucket (dev account)
        working-directory: frontend
        run: |
          npm run install-build-test-deploy
  frontend-create-haggadah:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: webapp
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEV_ROLE_ARN }}
          aws-region: us-east-1
      - name: Deploy to the frontend-create-haggadah bucket   (dev account)
        working-directory: frontend-create-haggadah
        run: |
          npm run install-build-test-deploy
  content:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: webapp
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEV_ROLE_ARN }}
          aws-region: us-east-1
      - name: Install content
        working-directory: content
        run: |
          npm install
      - name: Test content
        working-directory: content
        run: |
          npm test
      - name: itest content (SKIP)
        working-directory: content
        run: |
          echo "Skipping, as this tests the incomplete preview-Haggadah feature"
      #          npm run it
      - name: Deploy content
        working-directory: content
        run: |
          npm run deploy
  itest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [frontend, content]
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEV_ROLE_ARN }}
          aws-region: us-east-1
      - name: Install itest
        working-directory: itest
        run: |
          npm install
      - name: Run smoke test (dev account)
        working-directory: itest
        env:
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_REGION: "us-east-1"
        run: |
          npm run itest
  itest-links-2023:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [frontend, frontend-create-haggadah, content]
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEV_ROLE_ARN }}
          aws-region: us-east-1
      - name: Install itest
        working-directory: itest
        run: |
          npm install
      - name: Run itest on the v2 link-based flow, 2023 (dev account)
        working-directory: itest
        env:
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_REGION: "us-east-1"
          PARTICIPANTS_ARG: "12"
        run: |
          npm run itest-links
  itest-links-2022:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [frontend, frontend-create-haggadah, content]
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEV_ROLE_ARN }}
          aws-region: us-east-1
      - name: Install itest
        working-directory: itest
        run: |
          npm install
      - name: Run itest on the v2 link-based flow, 2022 (dev account)
        working-directory: itest
        env:
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_REGION: "us-east-1"
          SCRIPT_TERM: "2022_Script"
        run: |
          npm run itest-links
  itest-links-2019-magid:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [frontend, frontend-create-haggadah, content]
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEV_ROLE_ARN }}
          aws-region: us-east-1
      - name: Install itest
        working-directory: itest
        run: |
          npm install
      - name: Run itest on the v2 link-based flow, 2019 magid (dev account)
        working-directory: itest
        env:
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_REGION: "us-east-1"
          PARTICIPANTS_ARG: "8"
          SCRIPT_TERM: "2019_Magid"
        run: |
          npm run itest-links
