name: CI-feature-branch
concurrency: ci-${{ github.ref }}
on:
  push:
    branches: ["*", "!main", "!master", "!skip/*"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  id-account:
    runs-on: ubuntu-latest
    steps:
      - name: Identify dev account and region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          aws sts get-caller-identity
          echo ${AWS_DEFAULT_REGION} | sed 's/-/+/g'
  webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          persist-credentials: false
      - name: Install infra
        working-directory: infra
        run: |
          npm install
      - name: Install backend
        working-directory: backend
        run: |
          npm install
      - name: Test backend
        working-directory: backend
        run: |
          npm test
      - name: Install backend-v2
        working-directory: backend-v2
        run: |
          npm install
      - name: Test backend-v2
        working-directory: backend-v2
        run: |
          npm test
      - name: Build infra
        working-directory: infra
        run: |
          npm run build
      - name: Test infra
        working-directory: infra
        run: |
          npm test
      - name: Build backend prod artifact
        working-directory: backend
        run: |
          rm -rf node_modules
          npm install --production
      - name: Build backend-v2 prod artifact
        working-directory: backend-v2
        run: |
          rm -rf node_modules
          npm install --production
      - name: Deploy the webapp stack to dev account
        working-directory: infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          npm run deploy-webapp
  frontend:
    runs-on: ubuntu-latest
    needs: webapp
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy to the frontend bucket (dev account)
        working-directory: frontend
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          npm run install-build-test-deploy
  frontend-create-haggadah:
    runs-on: ubuntu-latest
    needs: webapp
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy to the frontend-create-haggadah bucket   (dev account)
        working-directory: frontend-create-haggadah
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets. DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets. DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
            npm run install-build-test-deploy
  content:
    runs-on: ubuntu-latest
    needs: webapp
    steps:
      - uses: actions/checkout@v3
      - name: Install content
        working-directory: content
        run: |
          npm install
      - name: Test content
        working-directory: content
        run: |
          npm test
      - name: itest content (SKIP)
        working-directory: content
        run: |
          echo "Skipping, as this tests the incomplete preview-Haggadah feature"
#          npm run it
      - name: Deploy content
        working-directory: content
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          npm run deploy
  itest:
    runs-on: ubuntu-latest
    needs: [frontend, content]
    steps:
      - uses: actions/checkout@v3
      - name: Install itest
        working-directory: itest
        run: |
          npm install
      - name: Run smoke test (dev account)
        working-directory: itest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_REGION: "us-east-1"
        run: |
          npm run itest
  itest-links:
    runs-on: ubuntu-latest
    needs: [frontend, frontend-create-haggadah, content]
    steps:
      - uses: actions/checkout@v3
      - name: Install itest
        working-directory: itest
        run: |
          npm install
      - name: Run smoke test (dev account)
        working-directory: itest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_REGION: "us-east-1"
        run: |
          npm run itest-links
