name: CI
concurrency: ci-${{ github.ref }}
on:
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
        with:
          submodules: true
          persist-credentials: false

      - name: Install
        run: |
          npm install

      - name: Install frontend
        working-directory: frontend
        run: |
          npm install

      - name: Install backend
        working-directory: backend
        run: |
          npm install

      - name: Test backend
        working-directory: backend
        run: |
          npm test

      - name: Build
        run: |
          npm run build

      - name: Build frontend
        working-directory: frontend
        run: |
          npm run build

      - name: Test frontend
        working-directory: frontend
        run: |
          npm test

      - name: Install content
        working-directory: content
        run: |
          npm install

      - name: Test content
        working-directory: content
        run: |
          npm test

      - name: Test (top-level)
        run: |
          npm test

      - name: Build backend prod artifact
        working-directory: backend
        run: |
          rm -rf node_modules
          npm install --production

      - name: Identity provider app secret roll call
        env:
          FACEBOOK_APP_SECRET: ${{ secrets.FACEBOOK_APP_SECRET }}
          GOOGLE_APP_SECRET: ${{ secrets.GOOGLE_APP_SECRET }}
          AMAZON_APP_SECRET: ${{ secrets.AMAZON_APP_SECRET }}
          APPLE_APP_SECRET: ${{ secrets.APPLE_APP_SECRET }}
        run: |
          node scripts/idp-app-secret-roll-call.js

      - name: Identify test account and region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          aws sts get-caller-identity
          echo ${AWS_DEFAULT_REGION} | sed 's/-/+/g'

      - name: Deploy the webapp stack to the test account
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          npm run deploy-webapp

      - name: Deploy to the frontend bucket (test account)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          npm run deploy-frontend

      - name: Deploy content (test account)
        working-directory: content
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          npm run deploy

      - name: Install itest
        working-directory: itest
        run: |
          npm install

      - name: Run integration tests, test account
        working-directory: scripts
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_REGION: "us-east-1"
        run: |
          npm run itest

      - name: Identify prod account and region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          aws sts get-caller-identity
          echo ${AWS_DEFAULT_REGION} | sed 's/-/+/g'

      - name: Deploy the webapp stack to the prod account
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          npm run deploy-webapp

      - name: Deploy to the frontend bucket (prod account)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          npm run deploy-frontend

      - name: Deploy content (prod account)
        working-directory: content
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          npm run deploy

      - name: Run integration tests, prod account
        working-directory: scripts
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_REGION: "us-east-1"
        run: |
          npm run itest

      - name: Identify prod2 account and region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD2_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD2_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          aws sts get-caller-identity
          echo ${AWS_DEFAULT_REGION} | sed 's/-/+/g'

      - name: Deploy the webapp stack to the prod2 account
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD2_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD2_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          npm run deploy-webapp

      - name: Deploy to the frontend bucket (prod2 account)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD2_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD2_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          npm run deploy-frontend

      - name: Deploy content (prod2 account)
        working-directory: content
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD2_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD2_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          npm run deploy

      - name: Run integration tests, prod2 account
        working-directory: scripts
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD2_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD2_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_REGION: "us-east-1"
        run: |
          npm run itest
  deploy-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: placeholder
        run: |
          true
  itest-test:
    needs: deploy-test
    runs-on: ubuntu-latest
    steps:
      - name: placeholder
        run: |
          true
  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: placeholder
        run: |
          true
  itest-prod:
    needs: deploy-prod
    runs-on: ubuntu-latest
    steps:
      - name: placeholder
        run: |
          true
  deploy-prod2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: placeholder
        run: |
          true
  itest-prod2:
    needs: deploy-prod2
    runs-on: ubuntu-latest
    steps:
      - name: placeholder
        run: |
          true
